### ISSUE TITLE
Support multiple Elements (type: references)

### ISSUE THREAD

**Issue by paavo** [tmsdev/Tms.Select#1]
Support for type: reference**s** would be awesome

**Comment by jobee** [comment]
@paavo thank you for reporting this. Try to add `multiple: true` or use `type: array` in your settings.

```yaml
  properties:
    yourPropertyName:
      type: references # or use type "array"
      ui:
        inspector:
          editorOptions:
            multiple: true
```

also see https://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-string-array-string-selectboxeditor-dropdown-select-editor
