### ISSUE TITLE
BUG: Tms.Select does not respect dimensions

### ISSUE THREAD

**Issue by paavo** [tmsdev/Tms.Select#4]
Looks like Tms.Select does not respect dimensions. 

With the classic references i can only see and select Nodes which exist in the current Dimension - makes sense. 

After switching to Tms.Select I can see and select Nodes which do not exist in this Dimension. 
Even the Titles do not get translated. 
So it looks like the "default dimensions" are used @jobee?

**Comment by jobee** [comment]
Thank you @paavo for reporting this.
I've can't reproduce what you've described in my multi-dimension setups.
Tested Neos 7.1 & Neos 7.2

Could you please provide a little more insights on how your setup looks like? (Neos/UI version, YAML settings, Nodetree structure)

**Comment by paavo** [comment]
I have a Property `products` where you can reference multiple Products `Vendor.Project:Document.Product`

The standard references Element only shows Nodes of type `Vendor.Project:Document.Product` *who are existing*
Also the Product Titles are shown in the current Dimension

```
'Vendor.Project:Content.Element':
  ...
  properties:
    products:
      type: references
      ui:
        label: Product(s)
        showInCreationDialog: true
        reloadPageIfChanged: true
        inspector:
          group: settings
          editorOptions:
            nodeTypes: ['Vendor.Project:Document.Product']
```

After switching to tms/select i can see all `Vendor.Project:Document.Product` - even if they not exist in the current dimension.
Also the Product Titles are not localised (shown in default dimension i think)

```
'Vendor.Project:Content.Element':
  ...
  properties:
    products:
      type: references
      ui:
        label: Product(s)
        showInCreationDialog: true
        reloadPageIfChanged: true
        inspector:
          group: settings
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            multiple: true
            dataSourceIdentifier: 'tms-select-nodedata'
            dataSourceAdditionalData:
              nodeTypes: ['Vendor.Project:Document.Product']
```

We can have a Slack-Call and i can show you the Issue if this helps @jobee 

But first, have a good weekend 🎉
