### ISSUE TITLE
Make data source results sortable

### ISSUE THREAD

**Issue by jobee** [tmsdev/Tms.Select#6]
By default, the Flow query will sort the results by index (position in nodetree).
We need at least two more arguments to make sorting work.

```yaml
dataSourceAdditionalData:
  sortByProperty: 'title'
  sortOrder: 'ASC'
```
